### ISSUE TITLE
Is it possible to have multiple datasets in different colors in the same PCP?

### ISSUE THREAD

**Issue by Karlo-Emilo** [sgratzl/chartjs-chart-pcp#36]
Is it possible to have multiple datasets in different colors in the same PCP?

(In the newest version)

I remember that I have tried to use this library before to find out that it is not possible. But I may be wrong.

**Comment by sgratzl** [comment]
no since a chart.js dataset is already being used to represent one axis.

**Comment by Karlo-Emilo** [comment]
Thanks for the reply @sgratzl

Do you know of another way to separate the data into different color groups?

**Comment by sgratzl** [comment]
just published a patched version. now you should be able to define a context function similar to 

```js
borderColor: (ctx) => ctx.dataIndex < 10 ? 'red' : 'blue'
```

**Comment by Karlo-Emilo** [comment]
How cool! Looking forward to try it out. It may be a few weeks before I find the time, but I will let you know how well it worked for me if you do not close the issue.

Thanks for taking the time to do this! It is very much appreciated.
