### ISSUE TITLE
How can I create a Parallel Coordinate graph in the react?

### ISSUE THREAD

**Issue by niralivasoya** [sgratzl/chartjs-chart-pcp#43]
I want to use this library to create something like this in React: [https://plotly.com/javascript/parallel-coordinates-plot/](https://plotly.com/javascript/parallel-coordinates-plot/) Is this possible with this library?

Can you please suggest some steps to work with reactjs? 

Thanks.

**Comment by niralivasoya** [comment]
Hi @sgratzl can you please help?

**Comment by sgratzl** [comment]
you mean the static plot or the interactivity. 

I don't know a way to implement the axis slider
