### ISSUE TITLE
How to color/highlight a single dataset?

### ISSUE THREAD

**Issue by lunartec** [sgratzl/chartjs-chart-pcp#65]
I am struggling to find any means/documentation around being able to highlight a single dataset a different colour.

<img width="677" alt="Screenshot 2024-06-26 at 12 02 21" src="https://github.com/sgratzl/chartjs-chart-pcp/assets/88038154/b851cad9-07cc-4090-b53c-91ecfff2f405">

**Context**

- Version: chart.js@4+; chartjs-chart-pcp@4.3.1
- Browser: N/A

**Additional context**

I have a "core" dataset that I want to map on top of "similar" datasets and I need to highlight this particular line.

**Comment by lunartec** [comment]
As an update, the hover function is able to do this, I can programmatically set an active dataset but then the next hover will remove this - and I don't really want to use the hover style, I would rather be able to specify a datasetIndex and then set a `border-color,` I am guessing for each lineSegment?

**Comment by lunartec** [comment]
UPDATE AGAIN: borderColor is indexable so using an array got me there 👍 looks like thats the way to go.

**Comment by sgratzl** [comment]
you should also be able to provide a function instead of an array if that is easier for you
